name: aplicacao_unip

version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  permission_handler: ^10.2.0
  on_audio_query: ^2.6.1
  lite_rolling_switch: ^1.0.0
  http: ^0.13.5
  responsive_framework: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #pub.dev packages
  sqflite: ^2.0.2+1
  flutter_local_notifications: ^9.5.3+1
  dotted_border: ^2.0.0+2
  provider: ^6.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/color-circle.png
    - images/nuvem.png
    - images/umidificador.png
    - images/ventilador.png
    - images/galo.png
    - images/imagem3d.jpg
    - images/camaleao.png

  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
